- on-premise/email.md
- on-premise/install.md
1. add an email page to the docs
2. update install docs with correct sudo commands
> add emails docs & polish install docs

- api/items_post.md
Clubhouse link: [[ch7896]](https://app.clubhouse.io/rollbar/story/7896/pyrollbar-args-scrub-refactor)
> update items_post for argspec

- on-premises/requirements.md
Added sections on network ports and email needs, along with updated verbiage on the rest of the document.
> flesh out on-premise requirements

- tools/helpscout.md
Removed mention of Rollbar using Helpscout.
> updated helpscout.md

- api/overview.md
- update contact email address
- format and add more Examples links
> update links on /docs/api

- tools/github.md
Apparently I don't need to add /docs to the beginning of all image links...
> Fixing image links

- tools/gitlab.md
So I can fix a broken sidebar link.
> Updating image links

- guides/rql.md
cf. https://github.com/rollbar/mox/pull/1408
> basic documentation for 'IN'/'NOT IN'

- guides/enterprise-security-controls.md
I thought about adding screenshots to this but was worried that was exposing too much info. Thoughts?
> Adding docs on Enterprise Security Controls

- guides/source-maps.md
Don't merge this yet, I can't check this in dev to make sure it's all okay.
> Updating source maps docs with troubleshooting tips

- api/dsym.md
- api/proguard.md
> fix curl upload syntax

- guides/rql.md
@rivkahstandig3636 I made a few corrections and broke it into two sections, but could use your help wordsmithing. Lmk if any feedback!
> various updates to rql column docs

- guides/person-tracking.md
Ironic that my branch name is misspelled...
> Fix spelling

- guides/filtering-notifications.md
- guides/issue-tracking.md
- guides/resolving-via-commits.md
- guides/source-control.md
- tools/github.md
- tools/gitlab.md
> Github -> GitHub, Gitlab -> GitLab

- onboarding/php.md
I based this off of the[ notifier docs ](https://github.com/rollbar/rollbar-php/blob/master/README.md)
@rokob - Is this enough for a basic install? Am I missing anything important or should I remove anything unnecessary? 
@brianr
> Update php docs in onboarding flow

- guides/custom-log-messages.md
> Revert "add symbol to custom log messages guide"

- api/items_post.md
to adhere to ABNF for UUID string representation given in
["3. Namespace Registration Template" of RFC 4122](https://tools.ietf.org/html/rfc4122#section-3).
> Change example UUID

- guides/rql.md
https://app.clubhouse.io/rollbar/story/21655/add-platform-id-meaning-to-rql-docs
> Rql platform/framework ids

- onboarding/php.md
Reverted format of PHP docs to be similar to that of the previous version, but updated to use the latest version.
> Update php onboarding docs

- guides/custom-grouping.md
should this be in this section of the docs? let me know if it should be reworded.
> add explanation about custom fingerprinting

- api/items_post.md
For [CH24701](https://app.clubhouse.io/rollbar/story/24701/telemetry-update-api-post-docs)
I'd like to get this reviewed before merging.
> Adding telemetry API documentation

- onboarding/elixir.md
Will merge when I have the icons for Elixir and can deploy this.
> Adding Elixir to onboarding docs

- onboarding/wordpress.md
Will merge when I have the icons for Wordpress and can deploy this.
> Adding Wordpress to onboarding

- onboarding/android.md
- onboarding/java.md
Update Android & Java onboarding docs
> Java beta 3 onboarding

- guides/rql.md
Adding some more examples and clarifying GROUP BY. Also adding docs for count_distinct.
> Rql docs update

- guides/reduce-noisy-javascript-errors.md
> Fixing broken link and changing verbiage from custom grouping

- guides/grouping-algorithm.md
Awaiting confirmation from Artur that this is correct before I merge.
> Updating PHP fingerprinting example

- guides/notifications.md
- tools/ciscospark.md
Preparing docs for when Cisco Spark integration will be released.
I imagine will deploy both integration and documentation at the same time
> Add Spark docs [ch33896]

- onboarding/winforms.md
> fix winforms sample to new api

- onboarding/apex.md
Related to https://github.com/rollbar/mox/pull/5567
> Add apex framework to the onboarding

- onboarding/angular2.md
Fixes: https://github.com/rollbar/rollbar.js/issues/806
> Update sample for typescript 3.6.x

- .github/pull_request_template.md
> Add PR template to this repository

- onboarding/twisted.md
added twisted documentation
> Fix [#1]()
> added twisted documentation

- onboarding/django.md
Update Django example for versions newer than v1.10.
General cleanup.
> Fix [ch79984]
> Update Django onboarding docs

- onboarding/celery.md
As we are adding Celery framework to onboard page, this PR adds onboarding instructions for Celery.
The docs need some improvements in the future, once we consolidate all
frameworks docs.
> Fix [#1]()
> Add Celery onboarding instructions

- onboarding/go.md
Fixing go example
> Fix [#68715](https://app.clubhouse.io/rollbar/story/68715/update-go-onboarding-page)
> fixed go example

- onboarding/java.md
This PR adds comments to the Java onboarding code snippets, to provide context since the snippets cannot be fully self contained (eg. we cannot know the user's application's package so we cannot include that in the snippet.)
> Add comments providing context to Java onboarding code snippets.

- onboarding/python.md
Changes reflect updates provided by Design contain better consistency:
* https://app.clubhouse.io/rollbar/story/83057/python-highlight-docs-where-all-supported-frameworks-can-be-viewed
* https://app.clubhouse.io/rollbar/story/83062/python-copy-change-to-installation-section-of-setup-wizard
* https://app.clubhouse.io/rollbar/story/83227/python-remove-add-rollbar-to-your-python-application-text-block
> Description here
> Fix [#1]()
> Update python.md text

- onboarding/python.md
Fix typo and clean up the doc.
> Fix [#1]()
> Fix typo and break lines in Python onboarding instructions

- onboarding/fastapi.md
- onboarding/starlette.md
Add FastAPI and Starlette onboarding instructions.
> Fix [ch80783]
> Add FastAPI and Starlette onboarding instructions

- onboarding/starlette.md
Simplification of onboarding instructions. Removed redundant import.
> Fix [#1]()
> Starlette instructions: remove redundant import
